apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    name: redis-ha-master
    redis-sentinel: "true"
    redis-node: "true"
    role: master
    app: redis-ha
  name: redis-ha-master
spec:
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        redis-sentinel: "true"
        redis-node: "true"
        role: master
        app: redis-ha
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: master
          image: gcr.io/talk2vinocloud/redis:v1
          resources:
            limits:
              memory: 700Mi
            requests:
              cpu: 100m
              memory: 200Mi

          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379

          volumeMounts:
            - mountPath: /redis-master-data
              name: redis-master-data
        - name: sentinel
          image: gcr.io/talk2vinocloud/redis:v1-timeout
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi

          env:
            - name: SENTINEL
              value: "true"
          ports:
            - containerPort: 26379
  volumeClaimTemplates:
  - metadata:
      name: redis-master-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
