apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-ha
    role: service
    app: redis-ha
  name: redis-ha
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    redis-node: "true"
