apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-ha-sentinel-svc
    role: service
    app: redis-ha
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
